version: "3"
services:
  app:
    build: .
    ports:
      - 9090:9090
    depends_on:
      - db
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: postgres
  db:
    image: postgres:9.6.8
