version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0:8000
    depends_on:
      - db
      - redis
    entrypoint: entrypoint_web.sh
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: postgres
    ports:
      - 8000:8000
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A web worker -l info
    depends_on:
      - redis
    entrypoint: entrypoint_worker.sh
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: postgres
    links:
      - db
  db:
    image: postgres:9.6.8
  redis:
    image: redis:3.2.11
